TYPO3:
  Flow:
    security:
      authentication:
        providers:
          Typo3BackendProvider:
            requestPatterns:
              controllerObjectName: 'PackageFactory\Guevara\Controller\.*|TYPO3\Neos\Controller\.*|TYPO3\Neos\Service\.*|TYPO3\Media\Controller\.*'
  Neos:
    typoScript:
      autoInclude:
        'PackageFactory.Guevara': TRUE

  TypoScript:
    defaultContext:
      'Guevara.Activation': 'PackageFactory\Guevara\TypoScript\Helper\ActivationHelper'
PackageFactory:
  Guevara:
    asyncModuleMapping:
      'resource://PackageFactory.Guevara/Public/JavaScript/InspectorEditors.js':
        'Neos.UI:Inspector.TextField': true
        'Neos.UI:Inspector.Boolean': true
        'Neos.UI:Inspector.DateTime': true
        'Neos.UI:Inspector.Image': true
        'Neos.UI:Inspector.TextArea': true
        'Neos.UI:Inspector.SelectBox': true
        'Neos.UI:Inspector.NodeType': true
    legacyModuleMapping:
      'resource://PackageFactory.Guevara/Public/JavaScript/InspectorEditors.js':
        'TYPO3.Neos/Inspector/Editors/TextFieldEditor': 'Neos.UI:Inspector.TextField'
        'TYPO3.Neos/Inspector/Editors/BooleanEditor': 'Neos.UI:Inspector.Boolean'
        'TYPO3.Neos/Inspector/Editors/DateTimeEditor': 'Neos.UI:Inspector.DateTime'
        'TYPO3.Neos/Inspector/Editors/ImageEditor': 'Neos.UI:Inspector.Image'
        'TYPO3.Neos/Inspector/Editors/TextAreaEditor': 'Neos.UI:Inspector.TextArea'
        'TYPO3.Neos/Inspector/Editors/SelectBoxEditor': 'Neos.UI:Inspector.SelectBox'
        'TYPO3.Neos/Inspector/Editors/NodeTypeEditor': 'Neos.UI:Inspector.NodeType'
        'Content/Inspector/Editors/NodeTypeEditor': 'Neos.UI:Inspector.NodeType'

    # All PRIVATE, not meant for public extensibility.
    state:
      defaultEelContext:
        String: 'TYPO3\Eel\Helper\StringHelper'
        Array: 'TYPO3\Eel\Helper\ArrayHelper'
        Date: 'TYPO3\Eel\Helper\DateHelper'
        Configuration: 'TYPO3\Eel\Helper\ConfigurationHelper'
        Math: 'TYPO3\Eel\Helper\MathHelper'
        Json: 'TYPO3\Eel\Helper\JsonHelper'
        I18n: 'TYPO3\Flow\I18n\EelHelper\TranslationHelper'
        'Guevara.Workspace': 'PackageFactory\Guevara\TypoScript\Helper\WorkspaceHelper'
        'Guevara.NodeInfo': 'PackageFactory\Guevara\TypoScript\Helper\NodeInfoHelper'
        'Guevara.NodeTypes': 'PackageFactory\Guevara\TypoScript\Helper\NodeTypesHelper'

      documentNode:
        nodes: '${Guevara.NodeInfo.renderDocumentNodeAndChildContent(documentNode, controllerContext)}'
        metaData:
          contextPath: '${q(documentNode).property("_contextPath")}'
          previewUrl: '${Guevara.NodeInfo.uri(q(documentNode).context({workspaceName: "live"}).get(0), controllerContext)}'
      backend:
        changes:
          pending: []
          processing: []
          failed: []
        cr:
          nodeTypes:
            byName: ${Guevara.NodeTypes.nodeTypesByName()}
            constraints: ${Guevara.NodeTypes.nodeTypeConstraints()}
            inheritanceMap: ${Guevara.NodeTypes.nodeTypeInheritanceMap()}
            groups: ${Configuration.setting('TYPO3.Neos.nodeTypes.groups')}
          nodes:
            byContextPath: ${Guevara.NodeInfo.defaultNodesForBackend(site, documentNode, controllerContext)}
            siteNode: ${q(site).property('_contextPath')}
          workspaces:
            byName: ${Guevara.Workspace.initializeWorkspacesByName()}
            active: ${Guevara.Workspace.getPersonalWorkspaceName()}
#          images: # todo: move into "storage"
            #byUuid: []
        ui:
          contentCanvas:
            src: ${Guevara.NodeInfo.uri(documentNode, controllerContext)}
            contextPath: ${q(documentNode).property('_contextPath')}
          debugMode: false
          fullScreen:
            isFullScreen: false
          leftSideBar:
            isHidden: false
          rightSideBar:
            isHidden: false
          addNodeModal:
            referenceNode: ''
            mode: 'insert'
          drawer:
            isHidden: true
          pageTree:
            isLoading: false
            hasError: false
            focused: ${q(documentNode).property('_contextPath')}
            active: ${q(documentNode).property('_contextPath')}
          remote:
            isSaving: FALSE
            isPublishing: FALSE
            isDiscarding: FALSE
        user:
          name:
            title: ${q(user).property('name.title')}
            firstName: ${q(user).property('name.firstName')}
            middleName: ${q(user).property('name.middleName')}
            lastName: ${q(user).property('name.lastName')}
            otherName: ${q(user).property('name.otherName')}
            fullName: ${q(user).property('name.fullName')}
          settings:
            isAutoPublishingEnabled: false

    changes:
      types:
          'PackageFactory.Guevara:Property': 'PackageFactory\Guevara\Domain\Model\Changes\Property'
          'PackageFactory.Guevara:Create': 'PackageFactory\Guevara\Domain\Model\Changes\Create'
          'PackageFactory.Guevara:CreateBefore': 'PackageFactory\Guevara\Domain\Model\Changes\CreateBefore'
          'PackageFactory.Guevara:CreateAfter': 'PackageFactory\Guevara\Domain\Model\Changes\CreateAfter'
